stages:
  - test
  - upload

image: python:alpine

lint:
  stage: test
  script:
    - pip install flake8
    - flake8

test:
  stage: test
  script:
    - apk add git g++
    - pip install .
    - python setup.py test

upload:
  stage: upload
  only:
    - tags
  environment: pypi
  script:
    - apk add git
    - python setup.py check
    - python setup.py bdist_wheel sdist
    - twine upload dist/*
